version: '3.8' # or your desired Compose file version
services:
  db:
    image: postgres:latest # or a specific version like postgres:15
    restart: always
    environment:
      POSTGRES_USER: tanujgyan
      POSTGRES_PASSWORD: bbpwd
      POSTGRES_DB: stockmarket
    ports:
      - "5432:5432" # Expose the port (optional, for external access)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
